python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_activation_sparsifier.py
python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_composability.py
python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_data_scheduler.py
python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_data_sparsifier.py
python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_kernels.py
python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_parametrization.py
python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_qlinear_packed_params.py
python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_scheduler.py
python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_sparsifier.py
python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_sparsity_utils.py
python /media/nimashiri/SSD/pytorch/test/ao/sparsity/test_structured_sparsifier.py
python /media/nimashiri/SSD/pytorch/test/autograd/test_complex.py
python /media/nimashiri/SSD/pytorch/test/autograd/test_functional.py
python /media/nimashiri/SSD/pytorch/test/backends/xeon/test_launch.py
python /media/nimashiri/SSD/pytorch/test/benchmark_utils/test_benchmark_utils.py
python /media/nimashiri/SSD/pytorch/test/bottleneck_test/test_args.py
python /media/nimashiri/SSD/pytorch/test/bottleneck_test/test_cuda.py
python /media/nimashiri/SSD/pytorch/test/custom_backend/test_custom_backend.py
python /media/nimashiri/SSD/pytorch/test/custom_operator/test_custom_ops.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_pypg.py
python /media/nimashiri/SSD/pytorch/test/distributed/algorithms/ddp_comm_hooks/test_ddp_hooks.py
python /media/nimashiri/SSD/pytorch/test/distributed/algorithms/quantization/test_quantization.py
python /media/nimashiri/SSD/pytorch/test/distributed/algorithms/test_join.py
python /media/nimashiri/SSD/pytorch/test/distributed/bin/test_script.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_2d_fsdp_dt_checkpoint.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_checkpoint.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_dedup_tensors.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_dtensor_checkpoint.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_file_system_checkpoint.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_file_system_checkpoint_cpu.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_fsdp_model_state.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_fsdp_optim_state.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_fsspec.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_nested_dict.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_planner.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_traverse.py
python /media/nimashiri/SSD/pytorch/test/distributed/checkpoint/test_utils.py
python /media/nimashiri/SSD/pytorch/test/distributed/elastic/multiprocessing/bin/test_script.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_hybrid_shard.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_checkpoint_wrapper.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_distributed_checkpoint.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_apply.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_checkpoint.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_clip_grad_norm.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_comm.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_comm_hooks.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_core.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_dtensor_state_dict.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_exec_order.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_fine_tune.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_flatten_params.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_freezing_weights.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_fx.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_grad_acc.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_ignored_modules.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_input.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_memory.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_meta.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_misc.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_mixed_precision.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_multiple_forward.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_multiple_wrapping.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_optim_state.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_overlap.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_pure_fp16.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_sharded_grad_scaler.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_state_dict.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_tp_integration.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_traversal.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_uneven.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_unshard_params.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_fsdp_use_orig_params.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_shard_utils.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_utils.py
python /media/nimashiri/SSD/pytorch/test/distributed/fsdp/test_wrap.py
python /media/nimashiri/SSD/pytorch/test/distributed/launcher/bin/test_script.py
python /media/nimashiri/SSD/pytorch/test/distributed/launcher/bin/test_script_init_method.py
python /media/nimashiri/SSD/pytorch/test/distributed/launcher/bin/test_script_is_torchelastic_launched.py
python /media/nimashiri/SSD/pytorch/test/distributed/launcher/bin/test_script_local_rank.py
python /media/nimashiri/SSD/pytorch/test/distributed/nn/jit/test_instantiator.py
python /media/nimashiri/SSD/pytorch/test/distributed/optim/test_apply_optimizer_in_backward.py
python /media/nimashiri/SSD/pytorch/test/distributed/optim/test_named_optimizer.py
python /media/nimashiri/SSD/pytorch/test/distributed/optim/test_zero_redundancy_optimizer.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/skip/test_api.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/skip/test_gpipe.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/skip/test_inspect_skip_layout.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/skip/test_leak.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/skip/test_portal.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/skip/test_stash_pop.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/skip/test_tracker.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/skip/test_verify_skippables.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_balance.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_bugs.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_checkpoint.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_copy.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_deferred_batch_norm.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_dependency.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_inplace.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_microbatch.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_phony.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_pipe.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_pipeline.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_stream.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_transparency.py
python /media/nimashiri/SSD/pytorch/test/distributed/pipeline/sync/test_worker.py
python /media/nimashiri/SSD/pytorch/test/distributed/rpc/cuda/test_tensorpipe_agent.py
python /media/nimashiri/SSD/pytorch/test/distributed/rpc/test_faulty_agent.py
python /media/nimashiri/SSD/pytorch/test/distributed/rpc/test_share_memory.py
python /media/nimashiri/SSD/pytorch/test/distributed/rpc/test_tensorpipe_agent.py
python /media/nimashiri/SSD/pytorch/test/distributed/tensor/parallel/test_2d_parallel.py
python /media/nimashiri/SSD/pytorch/test/distributed/tensor/parallel/test_parallelize_api.py
python /media/nimashiri/SSD/pytorch/test/distributed/tensor/parallel/test_tp_examples.py
python /media/nimashiri/SSD/pytorch/test/distributed/tensor/parallel/test_tp_random_state.py
python /media/nimashiri/SSD/pytorch/test/distributed/tensor/parallel/test_tp_style.py
python /media/nimashiri/SSD/pytorch/test/distributed/tensor/parallel/test_view_sharding_dim_change.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_common.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_gloo.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_logger.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_nccl.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_object_collectives.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_spawn.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_spawn_gloo.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_spawn_nccl.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_spawn_ucc.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_c10d_ucc.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_collective_utils.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_data_parallel.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_distributed_spawn.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_dynamo_distributed.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_fake_pg.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_functional_api.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_inductor_collectives.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_launcher.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_multi_threaded_pg.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_nccl.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_pg_wrapper.py
python /media/nimashiri/SSD/pytorch/test/distributed/test_store.py
python /media/nimashiri/SSD/pytorch/test/distributed/_composable/fully_shard/test_fully_shard_init.py
python /media/nimashiri/SSD/pytorch/test/distributed/_composable/fully_shard/test_fully_shard_mixed_precision.py
python /media/nimashiri/SSD/pytorch/test/distributed/_composable/fully_shard/test_fully_shard_model_checkpoint.py
python /media/nimashiri/SSD/pytorch/test/distributed/_composable/fully_shard/test_fully_shard_optim_checkpoint.py
python /media/nimashiri/SSD/pytorch/test/distributed/_composable/fully_shard/test_fully_shard_runtime.py
python /media/nimashiri/SSD/pytorch/test/distributed/_composable/fully_shard/test_fully_shard_util.py
python /media/nimashiri/SSD/pytorch/test/distributed/_composable/test_checkpoint.py
python /media/nimashiri/SSD/pytorch/test/distributed/_composable/test_compose.py
python /media/nimashiri/SSD/pytorch/test/distributed/_composable/test_contract.py
python /media/nimashiri/SSD/pytorch/test/distributed/_composable/test_replicate.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharded_optim/test_sharded_optim.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharded_tensor/ops/test_binary_cmp.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharded_tensor/ops/test_embedding.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharded_tensor/ops/test_embedding_bag.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharded_tensor/ops/test_init.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharded_tensor/ops/test_tensor_ops.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharded_tensor/test_logger.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharded_tensor/test_sharded_tensor.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharded_tensor/test_sharded_tensor_reshard.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharding_plan/test_sharding_plan.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/sharding_spec/test_sharding_spec.py
python /media/nimashiri/SSD/pytorch/test/distributed/_shard/test_sharder.py
python /media/nimashiri/SSD/pytorch/test/distributed/_spmd/test_data_parallel.py
python /media/nimashiri/SSD/pytorch/test/distributed/_spmd/test_graph_utils.py
python /media/nimashiri/SSD/pytorch/test/distributed/_spmd/test_tracing.py
python /media/nimashiri/SSD/pytorch/test/distributed/_spmd/test_transformation.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/debug/test_op_coverage.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_api.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_basic_strategy.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_common_rules.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_device_mesh.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_dtensor.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_dtensor_ops.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_embedding_ops.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_init.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_math_ops.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_matrix_ops.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_pointwise_ops.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_random_ops.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_redistribute.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_tensor_ops.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_utils.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tensor/test_view_ops.py
python /media/nimashiri/SSD/pytorch/test/distributed/_tools/test_memory_tracker.py
python /media/nimashiri/SSD/pytorch/test/distributions/test_constraints.py
python /media/nimashiri/SSD/pytorch/test/distributions/test_distributions.py
python /media/nimashiri/SSD/pytorch/test/distributions/test_transforms.py
python /media/nimashiri/SSD/pytorch/test/distributions/test_utils.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_global.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_activation_checkpointing.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_after_aot.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_aot_autograd.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_autograd_function.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_backends.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_compile.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_comptime.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_config.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_ctx_manager.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_cudagraphs.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_decorators.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_dynamic_shapes.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_export.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_export_mutations.py