python /media/nimashiri/SSD/pytorch/test/onnx/test_fx_to_onnx_with_onnxruntime.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_fx_type_promotion.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_models.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_models_onnxruntime.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_models_quantized_onnxruntime.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_onnxscript_no_runtime.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_onnxscript_runtime.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_onnx_opset.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_operators.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_op_consistency.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_pytorch_jit_onnx.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_pytorch_onnx_no_runtime.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_pytorch_onnx_onnxruntime.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_pytorch_onnx_onnxruntime_cuda.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_pytorch_onnx_shape_inference.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_symbolic_helper.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_utility_funs.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_verification.py
python /media/nimashiri/SSD/pytorch/test/onnx_caffe2/test_caffe2_common.py
python /media/nimashiri/SSD/pytorch/test/onnx_caffe2/test_custom_ops.py
python /media/nimashiri/SSD/pytorch/test/onnx_caffe2/test_pytorch_helper.py
python /media/nimashiri/SSD/pytorch/test/onnx_caffe2/test_pytorch_onnx_caffe2.py
python /media/nimashiri/SSD/pytorch/test/onnx_caffe2/test_pytorch_onnx_caffe2_quantized.py
python /media/nimashiri/SSD/pytorch/test/onnx_caffe2/test_verify.py
python /media/nimashiri/SSD/pytorch/test/package/package_a/test_all_leaf_modules_tracer.py
python /media/nimashiri/SSD/pytorch/test/package/package_a/test_module.py
python /media/nimashiri/SSD/pytorch/test/package/package_a/test_nn_module.py
python /media/nimashiri/SSD/pytorch/test/package/package_c/test_module.py
python /media/nimashiri/SSD/pytorch/test/package/test_analyze.py
python /media/nimashiri/SSD/pytorch/test/package/test_dependency_api.py
python /media/nimashiri/SSD/pytorch/test/package/test_dependency_hooks.py
python /media/nimashiri/SSD/pytorch/test/package/test_digraph.py
python /media/nimashiri/SSD/pytorch/test/package/test_directory_reader.py
python /media/nimashiri/SSD/pytorch/test/package/test_glob_group.py
python /media/nimashiri/SSD/pytorch/test/package/test_importer.py
python /media/nimashiri/SSD/pytorch/test/package/test_load_bc_packages.py
python /media/nimashiri/SSD/pytorch/test/package/test_mangling.py
python /media/nimashiri/SSD/pytorch/test/package/test_misc.py
python /media/nimashiri/SSD/pytorch/test/package/test_model.py
python /media/nimashiri/SSD/pytorch/test/package/test_package_fx.py
python /media/nimashiri/SSD/pytorch/test/package/test_package_script.py
python /media/nimashiri/SSD/pytorch/test/package/test_repackage.py
python /media/nimashiri/SSD/pytorch/test/package/test_resources.py
python /media/nimashiri/SSD/pytorch/test/package/test_save_load.py
python /media/nimashiri/SSD/pytorch/test/profiler/test_memory_profiler.py
python /media/nimashiri/SSD/pytorch/test/profiler/test_profiler.py
python /media/nimashiri/SSD/pytorch/test/profiler/test_profiler_tree.py
python /media/nimashiri/SSD/pytorch/test/quantization/ao_migration/test_ao_migration.py
python /media/nimashiri/SSD/pytorch/test/quantization/ao_migration/test_quantization.py
python /media/nimashiri/SSD/pytorch/test/quantization/ao_migration/test_quantization_fx.py
python /media/nimashiri/SSD/pytorch/test/quantization/bc/test_backward_compatibility.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/experimental/test_bits.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/experimental/test_fake_quantize.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/experimental/test_linear.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/experimental/test_nonuniform_observer.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/experimental/test_quantized_tensor.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/experimental/test_quantizer.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/test_backend_config.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/test_docs.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/test_quantized_functional.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/test_quantized_module.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/test_quantized_op.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/test_quantized_tensor.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/test_top_level_apis.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/test_utils.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/test_workflow_module.py
python /media/nimashiri/SSD/pytorch/test/quantization/core/test_workflow_ops.py
python /media/nimashiri/SSD/pytorch/test/quantization/eager/test_bias_correction_eager.py
python /media/nimashiri/SSD/pytorch/test/quantization/eager/test_equalize_eager.py
python /media/nimashiri/SSD/pytorch/test/quantization/eager/test_fuse_eager.py
python /media/nimashiri/SSD/pytorch/test/quantization/eager/test_model_numerics.py
python /media/nimashiri/SSD/pytorch/test/quantization/eager/test_numeric_suite_eager.py
python /media/nimashiri/SSD/pytorch/test/quantization/eager/test_quantize_eager_ptq.py
python /media/nimashiri/SSD/pytorch/test/quantization/eager/test_quantize_eager_qat.py
python /media/nimashiri/SSD/pytorch/test/quantization/fx/test_equalize_fx.py
python /media/nimashiri/SSD/pytorch/test/quantization/fx/test_model_report_fx.py
python /media/nimashiri/SSD/pytorch/test/quantization/fx/test_numeric_suite_fx.py
python /media/nimashiri/SSD/pytorch/test/quantization/fx/test_quantize_fx.py
python /media/nimashiri/SSD/pytorch/test/quantization/fx/test_subgraph_rewriter.py
python /media/nimashiri/SSD/pytorch/test/quantization/jit/test_deprecated_jit_quant.py
python /media/nimashiri/SSD/pytorch/test/quantization/jit/test_fusion_passes.py
python /media/nimashiri/SSD/pytorch/test/quantization/jit/test_ondevice_quantization.py
python /media/nimashiri/SSD/pytorch/test/quantization/jit/test_quantize_jit.py
python /media/nimashiri/SSD/pytorch/test/quantization/pt2e/test_graph_utils.py
python /media/nimashiri/SSD/pytorch/test/quantization/pt2e/test_quantize_pt2e.py
python /media/nimashiri/SSD/pytorch/test/quantization/pt2e/test_quantize_pt2e_fx.py
python /media/nimashiri/SSD/pytorch/test/quantization/pt2e/test_x86inductor_quantizer.py
python /media/nimashiri/SSD/pytorch/test/test_ao_sparsity.py
python /media/nimashiri/SSD/pytorch/test/test_autocast.py
python /media/nimashiri/SSD/pytorch/test/test_autograd.py
python /media/nimashiri/SSD/pytorch/test/test_binary_ufuncs.py
python /media/nimashiri/SSD/pytorch/test/test_bundled_images.py
python /media/nimashiri/SSD/pytorch/test/test_bundled_inputs.py
python /media/nimashiri/SSD/pytorch/test/test_comparison_utils.py
python /media/nimashiri/SSD/pytorch/test/test_compile_benchmark_util.py
python /media/nimashiri/SSD/pytorch/test/test_complex.py
python /media/nimashiri/SSD/pytorch/test/test_cpp_api_parity.py
python /media/nimashiri/SSD/pytorch/test/test_cpp_extensions_aot.py
python /media/nimashiri/SSD/pytorch/test/test_cpp_extensions_jit.py
python /media/nimashiri/SSD/pytorch/test/test_cpp_extensions_open_device_registration.py
python /media/nimashiri/SSD/pytorch/test/test_cuda.py
python /media/nimashiri/SSD/pytorch/test/test_cuda_expandable_segments.py
python /media/nimashiri/SSD/pytorch/test/test_cuda_multigpu.py
python /media/nimashiri/SSD/pytorch/test/test_cuda_nvml_based_avail.py
python /media/nimashiri/SSD/pytorch/test/test_cuda_primary_ctx.py
python /media/nimashiri/SSD/pytorch/test/test_cuda_sanitizer.py
python /media/nimashiri/SSD/pytorch/test/test_cuda_trace.py
python /media/nimashiri/SSD/pytorch/test/test_custom_op_testing.py
python /media/nimashiri/SSD/pytorch/test/test_dataloader.py
python /media/nimashiri/SSD/pytorch/test/test_datapipe.py
python /media/nimashiri/SSD/pytorch/test/test_decomp.py
python /media/nimashiri/SSD/pytorch/test/optim/test_lrscheduler.py
python /media/nimashiri/SSD/pytorch/test/optim/test_optim.py
python /media/nimashiri/SSD/pytorch/test/optim/test_swa_utils.py
python /media/nimashiri/SSD/pytorch/test/test_content_store.py
python /media/nimashiri/SSD/pytorch/test/test_deploy.py
python /media/nimashiri/SSD/pytorch/test/test_fx_passes.py
python /media/nimashiri/SSD/pytorch/test/test_jit_profiling.py
python /media/nimashiri/SSD/pytorch/test/test_mobile_optimizer.py
python /media/nimashiri/SSD/pytorch/test/test_nvfuser_dynamo.py
python /media/nimashiri/SSD/pytorch/test/test_quantization.py
python /media/nimashiri/SSD/pytorch/test/test_sympy_utils.py
python /media/nimashiri/SSD/pytorch/test/test_determination.py
python /media/nimashiri/SSD/pytorch/test/test_dispatch.py
python /media/nimashiri/SSD/pytorch/test/test_dlpack.py
python /media/nimashiri/SSD/pytorch/test/test_dynamic_shapes.py
python /media/nimashiri/SSD/pytorch/test/test_expanded_weights.py
python /media/nimashiri/SSD/pytorch/test/test_fake_tensor.py
python /media/nimashiri/SSD/pytorch/test/test_flop_counter.py
python /media/nimashiri/SSD/pytorch/test/test_foreach.py
python /media/nimashiri/SSD/pytorch/test/test_functionalization.py
python /media/nimashiri/SSD/pytorch/test/test_functionalization_of_rng_ops.py
python /media/nimashiri/SSD/pytorch/test/test_functional_autograd_benchmark.py
python /media/nimashiri/SSD/pytorch/test/test_functional_optim.py
python /media/nimashiri/SSD/pytorch/test/test_function_schema.py
python /media/nimashiri/SSD/pytorch/test/test_futures.py
python /media/nimashiri/SSD/pytorch/test/test_fx.py
python /media/nimashiri/SSD/pytorch/test/test_fx_experimental.py
python /media/nimashiri/SSD/pytorch/test/test_fx_reinplace_pass.py
python /media/nimashiri/SSD/pytorch/test/test_hub.py
python /media/nimashiri/SSD/pytorch/test/test_import_stats.py
python /media/nimashiri/SSD/pytorch/test/test_indexing.py
python /media/nimashiri/SSD/pytorch/test/test_itt.py
python /media/nimashiri/SSD/pytorch/test/test_jit.py
python /media/nimashiri/SSD/pytorch/test/test_jiterator.py
python /media/nimashiri/SSD/pytorch/test/test_jit_autocast.py
python /media/nimashiri/SSD/pytorch/test/test_jit_cuda_fuser.py
python /media/nimashiri/SSD/pytorch/test/test_jit_disabled.py
python /media/nimashiri/SSD/pytorch/test/test_jit_fuser.py
python /media/nimashiri/SSD/pytorch/test/test_jit_fuser_legacy.py
python /media/nimashiri/SSD/pytorch/test/test_jit_fuser_te.py
python /media/nimashiri/SSD/pytorch/test/test_jit_legacy.py
python /media/nimashiri/SSD/pytorch/test/test_jit_llga_fuser.py
python /media/nimashiri/SSD/pytorch/test/test_jit_simple.py
python /media/nimashiri/SSD/pytorch/test/test_jit_string.py
python /media/nimashiri/SSD/pytorch/test/test_kernel_launch_checks.py
python /media/nimashiri/SSD/pytorch/test/test_legacy_vmap.py
python /media/nimashiri/SSD/pytorch/test/test_license.py
python /media/nimashiri/SSD/pytorch/test/test_linalg.py
python /media/nimashiri/SSD/pytorch/test/test_logging.py
python /media/nimashiri/SSD/pytorch/test/test_masked.py
python /media/nimashiri/SSD/pytorch/test/test_maskedtensor.py
python /media/nimashiri/SSD/pytorch/test/test_matmul_cuda.py
python /media/nimashiri/SSD/pytorch/test/test_meta.py
python /media/nimashiri/SSD/pytorch/test/test_metal.py
python /media/nimashiri/SSD/pytorch/test/test_mkldnn.py
python /media/nimashiri/SSD/pytorch/test/test_mkldnn_fusion.py
python /media/nimashiri/SSD/pytorch/test/test_mkldnn_verbose.py
python /media/nimashiri/SSD/pytorch/test/test_mkl_verbose.py
python /media/nimashiri/SSD/pytorch/test/test_model_dump.py
python /media/nimashiri/SSD/pytorch/test/test_modules.py
python /media/nimashiri/SSD/pytorch/test/test_module_init.py
python /media/nimashiri/SSD/pytorch/test/test_monitor.py
python /media/nimashiri/SSD/pytorch/test/test_mps.py
python /media/nimashiri/SSD/pytorch/test/test_multiprocessing.py
python /media/nimashiri/SSD/pytorch/test/test_multiprocessing_spawn.py
python /media/nimashiri/SSD/pytorch/test/test_namedtensor.py
python /media/nimashiri/SSD/pytorch/test/test_namedtuple_return_api.py
python /media/nimashiri/SSD/pytorch/test/test_native_functions.py
python /media/nimashiri/SSD/pytorch/test/test_native_mha.py
python /media/nimashiri/SSD/pytorch/test/test_nestedtensor.py
python /media/nimashiri/SSD/pytorch/test/test_nn.py
python /media/nimashiri/SSD/pytorch/test/test_nnapi.py
python /media/nimashiri/SSD/pytorch/test/test_numba_integration.py
python /media/nimashiri/SSD/pytorch/test/test_numpy_interop.py
python /media/nimashiri/SSD/pytorch/test/test_nvfuser_frontend.py
python /media/nimashiri/SSD/pytorch/test/test_openmp.py
python /media/nimashiri/SSD/pytorch/test/test_ops.py
python /media/nimashiri/SSD/pytorch/test/test_ops_fwd_gradients.py
python /media/nimashiri/SSD/pytorch/test/test_ops_gradients.py
python /media/nimashiri/SSD/pytorch/test/test_ops_jit.py
python /media/nimashiri/SSD/pytorch/test/test_optim.py
python /media/nimashiri/SSD/pytorch/test/test_overrides.py
python /media/nimashiri/SSD/pytorch/test/test_package.py
python /media/nimashiri/SSD/pytorch/test/test_per_overload_api.py
python /media/nimashiri/SSD/pytorch/test/test_prims.py
python /media/nimashiri/SSD/pytorch/test/test_proxy_tensor.py
python /media/nimashiri/SSD/pytorch/test/test_pruning_op.py
python /media/nimashiri/SSD/pytorch/test/test_public_bindings.py
python /media/nimashiri/SSD/pytorch/test/test_python_dispatch.py
python /media/nimashiri/SSD/pytorch/test/test_pytree.py
python /media/nimashiri/SSD/pytorch/test/test_reductions.py
python /media/nimashiri/SSD/pytorch/test/test_scatter_gather_ops.py
python /media/nimashiri/SSD/pytorch/test/test_schema_check.py
python /media/nimashiri/SSD/pytorch/test/test_segment_reductions.py
python /media/nimashiri/SSD/pytorch/test/test_serialization.py
python /media/nimashiri/SSD/pytorch/test/test_set_default_mobile_cpu_allocator.py
python /media/nimashiri/SSD/pytorch/test/test_shape_ops.py
python /media/nimashiri/SSD/pytorch/test/test_show_pickle.py
python /media/nimashiri/SSD/pytorch/test/test_sort_and_select.py
python /media/nimashiri/SSD/pytorch/test/test_sparse.py
python /media/nimashiri/SSD/pytorch/test/test_sparse_csr.py
python /media/nimashiri/SSD/pytorch/test/test_sparse_semi_structured.py
python /media/nimashiri/SSD/pytorch/test/test_spectral_ops.py
python /media/nimashiri/SSD/pytorch/test/test_stateless.py
python /media/nimashiri/SSD/pytorch/test/test_static_runtime.py
python /media/nimashiri/SSD/pytorch/test/test_subclass.py
python /media/nimashiri/SSD/pytorch/test/test_tensorboard.py
python /media/nimashiri/SSD/pytorch/test/test_tensorexpr.py
python /media/nimashiri/SSD/pytorch/test/test_tensorexpr_pybind.py
python /media/nimashiri/SSD/pytorch/test/test_tensor_creation_ops.py
python /media/nimashiri/SSD/pytorch/test/test_testing.py
python /media/nimashiri/SSD/pytorch/test/test_throughput_benchmark.py
python /media/nimashiri/SSD/pytorch/test/test_torch.py
python /media/nimashiri/SSD/pytorch/test/test_transformers.py
python /media/nimashiri/SSD/pytorch/test/test_type_hints.py
python /media/nimashiri/SSD/pytorch/test/test_type_info.py
python /media/nimashiri/SSD/pytorch/test/test_type_promotion.py
python /media/nimashiri/SSD/pytorch/test/test_typing.py
python /media/nimashiri/SSD/pytorch/test/test_unary_ufuncs.py
python /media/nimashiri/SSD/pytorch/test/test_utils.py
python /media/nimashiri/SSD/pytorch/test/test_view_ops.py
python /media/nimashiri/SSD/pytorch/test/test_vulkan.py
python /media/nimashiri/SSD/pytorch/test/test_weak.py
python /media/nimashiri/SSD/pytorch/test/test_xnnpack_integration.py
python /media/nimashiri/SSD/pytorch/test/_nvfuser/test_dynamo.py
python /media/nimashiri/SSD/pytorch/test/_nvfuser/test_python_frontend.py
python /media/nimashiri/SSD/pytorch/test/_nvfuser/test_torchscript.py
python /media/nimashiri/SSD/pytorch/test/_test_bazel.py
