python /media/nimashiri/SSD/pytorch/test/dynamo/test_functions.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_higher_order_ops.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_input_attr_tracking.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_interop.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_logging.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_minifier.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_misc.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_model_output.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_modules.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_nops.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_optimizers.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_pre_dispatch.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_profiler.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_python_autograd.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_recompiles.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_recompile_ux.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_replay_record.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_repros.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_skip_non_tensor.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_sources.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_subgraphs.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_unspec.py
python /media/nimashiri/SSD/pytorch/test/dynamo/test_verify_correctness.py
python /media/nimashiri/SSD/pytorch/test/export/test_db.py
python /media/nimashiri/SSD/pytorch/test/export/test_export.py
python /media/nimashiri/SSD/pytorch/test/export/test_funtionalized_assertions.py
python /media/nimashiri/SSD/pytorch/test/export/test_passes.py
python /media/nimashiri/SSD/pytorch/test/export/test_pass_infra.py
python /media/nimashiri/SSD/pytorch/test/export/test_serialize.py
python /media/nimashiri/SSD/pytorch/test/export/test_upgrade.py
python /media/nimashiri/SSD/pytorch/test/export/test_verifier.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_aotdispatch.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_control_flow.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_dims.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_eager_transforms.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_logging.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_memory_efficient_fusion.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_minifier.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_ops.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_parsing.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_rearrange.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_vmap.py
python /media/nimashiri/SSD/pytorch/test/functorch/test_vmap_registrations.py
python /media/nimashiri/SSD/pytorch/test/fx/test_common_passes.py
python /media/nimashiri/SSD/pytorch/test/fx/test_cse_pass.py
python /media/nimashiri/SSD/pytorch/test/fx/test_dce_pass.py
python /media/nimashiri/SSD/pytorch/test/fx/test_future.py
python /media/nimashiri/SSD/pytorch/test/fx/test_fx_const_fold.py
python /media/nimashiri/SSD/pytorch/test/fx/test_fx_param_shape_control_flow.py
python /media/nimashiri/SSD/pytorch/test/fx/test_gradual_type.py
python /media/nimashiri/SSD/pytorch/test/fx/test_matcher_utils.py
python /media/nimashiri/SSD/pytorch/test/fx/test_pass_infra.py
python /media/nimashiri/SSD/pytorch/test/fx/test_source_matcher_utils.py
python /media/nimashiri/SSD/pytorch/test/fx/test_subgraph_rewriter.py
python /media/nimashiri/SSD/pytorch/test/fx/test_z3_gradual_types.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_kernel_benchmark.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_config.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_coordinate_descent_tuner.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_cpp_wrapper.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_cpu_repro.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_cudagraph_trees.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_cuda_repro.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_foreach.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_fused_attention.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_fx_fusion.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_indexing.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_inductor_freezing.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_layout_optim.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_max_autotune.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_minifier.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_minifier_isolate.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_mkldnn_pattern_matcher.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_pattern_matcher.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_perf.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_profiler.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_select_algorithm.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_smoke.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_split_cat_fx_passes.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_standalone_compile.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_torchinductor.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_torchinductor_codegen_dynamic_shapes.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_torchinductor_dynamic_shapes.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_torchinductor_opinfo.py
python /media/nimashiri/SSD/pytorch/test/inductor/test_triton_wrapper.py
python /media/nimashiri/SSD/pytorch/test/jit/fixtures_srcs/test_upgrader_models_generation.py
python /media/nimashiri/SSD/pytorch/test/jit/test_alias_analysis.py
python /media/nimashiri/SSD/pytorch/test/jit/test_async.py
python /media/nimashiri/SSD/pytorch/test/jit/test_aten_pow.py
python /media/nimashiri/SSD/pytorch/test/jit/test_attr.py
python /media/nimashiri/SSD/pytorch/test/jit/test_autodiff.py
python /media/nimashiri/SSD/pytorch/test/jit/test_autodiff_subgraph_slicing.py
python /media/nimashiri/SSD/pytorch/test/jit/test_await.py
python /media/nimashiri/SSD/pytorch/test/jit/test_backends.py
python /media/nimashiri/SSD/pytorch/test/jit/test_backend_nnapi.py
python /media/nimashiri/SSD/pytorch/test/jit/test_batch_mm.py
python /media/nimashiri/SSD/pytorch/test/jit/test_builtins.py
python /media/nimashiri/SSD/pytorch/test/jit/test_class_type.py
python /media/nimashiri/SSD/pytorch/test/jit/test_complex.py
python /media/nimashiri/SSD/pytorch/test/jit/test_convert_activation.py
python /media/nimashiri/SSD/pytorch/test/jit/test_cuda.py
python /media/nimashiri/SSD/pytorch/test/jit/test_custom_operators.py
python /media/nimashiri/SSD/pytorch/test/jit/test_dataclasses.py
python /media/nimashiri/SSD/pytorch/test/jit/test_data_parallel.py
python /media/nimashiri/SSD/pytorch/test/jit/test_dce.py
python /media/nimashiri/SSD/pytorch/test/jit/test_device_analysis.py
python /media/nimashiri/SSD/pytorch/test/jit/test_dtype_analysis.py
python /media/nimashiri/SSD/pytorch/test/jit/test_enum.py
python /media/nimashiri/SSD/pytorch/test/jit/test_exception.py
python /media/nimashiri/SSD/pytorch/test/jit/test_freezing.py
python /media/nimashiri/SSD/pytorch/test/jit/test_functional_blocks.py
python /media/nimashiri/SSD/pytorch/test/jit/test_fuser_common.py
python /media/nimashiri/SSD/pytorch/test/jit/test_graph_rewrite_passes.py
python /media/nimashiri/SSD/pytorch/test/jit/test_hash.py
python /media/nimashiri/SSD/pytorch/test/jit/test_hooks.py
python /media/nimashiri/SSD/pytorch/test/jit/test_ignorable_args.py
python /media/nimashiri/SSD/pytorch/test/jit/test_ignore_context_manager.py
python /media/nimashiri/SSD/pytorch/test/jit/test_isinstance.py
python /media/nimashiri/SSD/pytorch/test/jit/test_ivalue.py
python /media/nimashiri/SSD/pytorch/test/jit/test_jit_utils.py
python /media/nimashiri/SSD/pytorch/test/jit/test_list_dict.py
python /media/nimashiri/SSD/pytorch/test/jit/test_logging.py
python /media/nimashiri/SSD/pytorch/test/jit/test_misc.py
python /media/nimashiri/SSD/pytorch/test/jit/test_models.py
python /media/nimashiri/SSD/pytorch/test/jit/test_modules.py
python /media/nimashiri/SSD/pytorch/test/jit/test_module_apis.py
python /media/nimashiri/SSD/pytorch/test/jit/test_module_containers.py
python /media/nimashiri/SSD/pytorch/test/jit/test_module_interface.py
python /media/nimashiri/SSD/pytorch/test/jit/test_optimize_for_mobile_preserve_debug_info.py
python /media/nimashiri/SSD/pytorch/test/jit/test_op_decompositions.py
python /media/nimashiri/SSD/pytorch/test/jit/test_parametrization.py
python /media/nimashiri/SSD/pytorch/test/jit/test_peephole.py
python /media/nimashiri/SSD/pytorch/test/jit/test_profiler.py
python /media/nimashiri/SSD/pytorch/test/jit/test_python_bindings.py
python /media/nimashiri/SSD/pytorch/test/jit/test_python_builtins.py
python /media/nimashiri/SSD/pytorch/test/jit/test_python_ir.py
python /media/nimashiri/SSD/pytorch/test/jit/test_recursive_script.py
python /media/nimashiri/SSD/pytorch/test/jit/test_remove_mutation.py
python /media/nimashiri/SSD/pytorch/test/jit/test_save_load.py
python /media/nimashiri/SSD/pytorch/test/jit/test_save_load_for_op_version.py
python /media/nimashiri/SSD/pytorch/test/jit/test_scriptmod_ann.py
python /media/nimashiri/SSD/pytorch/test/jit/test_script_profile.py
python /media/nimashiri/SSD/pytorch/test/jit/test_slice.py
python /media/nimashiri/SSD/pytorch/test/jit/test_sparse.py
python /media/nimashiri/SSD/pytorch/test/jit/test_string_formatting.py
python /media/nimashiri/SSD/pytorch/test/jit/test_symbolic_shape_analysis.py
python /media/nimashiri/SSD/pytorch/test/jit/test_tensor_creation_ops.py
python /media/nimashiri/SSD/pytorch/test/jit/test_tensor_methods.py
python /media/nimashiri/SSD/pytorch/test/jit/test_torchbind.py
python /media/nimashiri/SSD/pytorch/test/jit/test_tracer.py
python /media/nimashiri/SSD/pytorch/test/jit/test_types.py
python /media/nimashiri/SSD/pytorch/test/jit/test_type_sharing.py
python /media/nimashiri/SSD/pytorch/test/jit/test_typing.py
python /media/nimashiri/SSD/pytorch/test/jit/test_union.py
python /media/nimashiri/SSD/pytorch/test/jit/test_unsupported_ops.py
python /media/nimashiri/SSD/pytorch/test/jit/test_upgraders.py
python /media/nimashiri/SSD/pytorch/test/jit/test_warn.py
python /media/nimashiri/SSD/pytorch/test/jit/test_with.py
python /media/nimashiri/SSD/pytorch/test/jit/xnnpack/test_xnnpack_delegate.py
python /media/nimashiri/SSD/pytorch/test/jit/test_complexity.py
python /media/nimashiri/SSD/pytorch/test/jit/test_hooks_modules.py
python /media/nimashiri/SSD/pytorch/test/jit/test_pdt.py
python /media/nimashiri/SSD/pytorch/test/lazy/test_bindings.py
python /media/nimashiri/SSD/pytorch/test/lazy/test_debug_util.py
python /media/nimashiri/SSD/pytorch/test/lazy/test_extract_compiled_graph.py
python /media/nimashiri/SSD/pytorch/test/lazy/test_meta_kernel.py
python /media/nimashiri/SSD/pytorch/test/lazy/test_reuse_ir.py
python /media/nimashiri/SSD/pytorch/test/lazy/test_step_closures.py
python /media/nimashiri/SSD/pytorch/test/lazy/test_ts_opinfo.py
python /media/nimashiri/SSD/pytorch/test/mobile/model_test/gen_test_model.py
python /media/nimashiri/SSD/pytorch/test/mobile/nnc/aot_test_model.py
python /media/nimashiri/SSD/pytorch/test/mobile/test_bytecode.py
python /media/nimashiri/SSD/pytorch/test/mobile/test_lite_script_module.py
python /media/nimashiri/SSD/pytorch/test/mobile/test_lite_script_type.py
python /media/nimashiri/SSD/pytorch/test/mobile/test_quantize_fx_lite_script_module.py
python /media/nimashiri/SSD/pytorch/test/mobile/test_upgraders.py
python /media/nimashiri/SSD/pytorch/test/mobile/test_upgrader_codegen.py
python /media/nimashiri/SSD/pytorch/test/nn/test_convolution.py
python /media/nimashiri/SSD/pytorch/test/nn/test_dropout.py
python /media/nimashiri/SSD/pytorch/test/nn/test_embedding.py
python /media/nimashiri/SSD/pytorch/test/nn/test_init.py
python /media/nimashiri/SSD/pytorch/test/nn/test_lazy_modules.py
python /media/nimashiri/SSD/pytorch/test/nn/test_module_hooks.py
python /media/nimashiri/SSD/pytorch/test/nn/test_multihead_attention.py
python /media/nimashiri/SSD/pytorch/test/nn/test_packed_sequence.py
python /media/nimashiri/SSD/pytorch/test/nn/test_parametrization.py
python /media/nimashiri/SSD/pytorch/test/nn/test_pooling.py
python /media/nimashiri/SSD/pytorch/test/nn/test_pruning.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_fx_to_onnx.py
python /media/nimashiri/SSD/pytorch/test/onnx/dynamo/test_exporter_api.py
python /media/nimashiri/SSD/pytorch/test/onnx/dynamo/test_registry_dispatcher.py
python /media/nimashiri/SSD/pytorch/test/onnx/internal/test_beartype.py
python /media/nimashiri/SSD/pytorch/test/onnx/internal/test_diagnostics.py
python /media/nimashiri/SSD/pytorch/test/onnx/internal/test_registraion.py
python /media/nimashiri/SSD/pytorch/test/onnx/onnx_test_common.py
python /media/nimashiri/SSD/pytorch/test/onnx/pytorch_test_common.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_autograd_funs.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_custom_ops.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_export_modes.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_fx_op_consistency.py
python /media/nimashiri/SSD/pytorch/test/onnx/test_fx_passes.py