#!/bin/bash

# export PYTHONPATH="/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/home/nimashiri/.local/lib/python3.8/site-packages:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages"

# echo $PYTHONPATH

python3 tensorflow/tensorflow/python/keras/optimizer_v2/ftrl_test.py
python3 tensorflow/tensorflow/python/keras/optimizer_v2/gradient_descent_test.py
python3 tensorflow/tensorflow/python/keras/optimizer_v2/learning_rate_schedule_test.py
python3 tensorflow/tensorflow/python/keras/optimizer_v2/legacy_learning_rate_decay_test.py
python3 tensorflow/tensorflow/python/keras/optimizer_v2/nadam_test.py
python3 tensorflow/tensorflow/python/keras/optimizer_v2/optimizer_v2_test.py
python3 tensorflow/tensorflow/python/keras/optimizer_v2/rmsprop_test.py
python3 tensorflow/tensorflow/python/keras/premade/linear_test.py
python3 tensorflow/tensorflow/python/keras/premade/wide_deep_test.py
python3 tensorflow/tensorflow/python/keras/preprocessing/image_dataset_test.py
python3 tensorflow/tensorflow/python/keras/preprocessing/image_test.py
python3 tensorflow/tensorflow/python/keras/preprocessing/sequence_test.py
python3 tensorflow/tensorflow/python/keras/preprocessing/text_dataset_test.py
python3 tensorflow/tensorflow/python/keras/preprocessing/text_test.py
python3 tensorflow/tensorflow/python/keras/preprocessing/timeseries_test.py
python3 tensorflow/tensorflow/python/keras/regularizers_test.py
python3 tensorflow/tensorflow/python/keras/saving/hdf5_format_test.py
python3 tensorflow/tensorflow/python/keras/saving/losses_serialization_test.py
python3 tensorflow/tensorflow/python/keras/saving/metrics_serialization_test.py
python3 tensorflow/tensorflow/python/keras/saving/saved_model/json_utils_test.py
python3 tensorflow/tensorflow/python/keras/saving/saved_model/revive_test.py
python3 tensorflow/tensorflow/python/keras/saving/saved_model/saved_model_test.py
python3 tensorflow/tensorflow/python/keras/saving/saved_model_experimental_test.py
python3 tensorflow/tensorflow/python/keras/saving/save_test.py
python3 tensorflow/tensorflow/python/keras/saving/saving_utils_test.py
python3 tensorflow/tensorflow/python/keras/tests/add_loss_correctness_test.py
python3 tensorflow/tensorflow/python/keras/tests/automatic_outside_compilation_test.py
python3 tensorflow/tensorflow/python/keras/tests/convert_to_constants_test.py
python3 tensorflow/tensorflow/python/keras/tests/custom_training_loop_test.py
python3 tensorflow/tensorflow/python/keras/tests/get_config_samples.py
python3 tensorflow/tensorflow/python/keras/tests/get_config_test.py
python3 tensorflow/tensorflow/python/keras/tests/graph_util_test.py
python3 tensorflow/tensorflow/python/keras/tests/integration_test.py
python3 tensorflow/tensorflow/python/keras/tests/memory_checker_test.py
python3 tensorflow/tensorflow/python/keras/tests/memory_test.py
python3 tensorflow/tensorflow/python/keras/tests/model_architectures.py
python3 tensorflow/tensorflow/python/keras/tests/model_architectures_test.py
python3 tensorflow/tensorflow/python/keras/tests/model_subclassing_compiled_test.py
python3 tensorflow/tensorflow/python/keras/tests/model_subclassing_test.py
python3 tensorflow/tensorflow/python/keras/tests/model_subclassing_test_util.py
python3 tensorflow/tensorflow/python/keras/tests/op_callbacks_test.py
python3 tensorflow/tensorflow/python/keras/tests/saved_model_test.py
python3 tensorflow/tensorflow/python/keras/tests/saver_test.py
python3 tensorflow/tensorflow/python/keras/tests/serialization_util_test.py
python3 tensorflow/tensorflow/python/keras/tests/summary_ops_test.py
python3 tensorflow/tensorflow/python/keras/tests/temporal_sample_weights_correctness_test.py
python3 tensorflow/tensorflow/python/keras/tests/tracking_test.py
python3 tensorflow/tensorflow/python/keras/tests/tracking_util_test.py
python3 tensorflow/tensorflow/python/keras/tests/tracking_util_with_v1_optimizers_test.py
python3 tensorflow/tensorflow/python/keras/tests/tracking_util_xla_test.py
python3 tensorflow/tensorflow/python/keras/utils/composite_tensor_support_test.py
python3 tensorflow/tensorflow/python/keras/utils/conv_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/data_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/generic_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/io_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/kernelized_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/layer_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/metrics_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/multi_gpu_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/np_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/tf_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/version_utils_test.py
python3 tensorflow/tensorflow/python/keras/utils/vis_utils_test.py
python3 tensorflow/tensorflow/python/keras/wrappers/scikit_learn_test.py
python3 tensorflow/tensorflow/python/layers/utils_test.py
python3 tensorflow/tensorflow/python/lib/core/bfloat16_test.py
python3 tensorflow/tensorflow/python/lib/io/file_io_test.py
python3 tensorflow/tensorflow/python/lib/io/tf_record_test.py
python3 tensorflow/tensorflow/python/module/module_test.py
python3 tensorflow/tensorflow/python/ops/array_ops_test.py
python3 tensorflow/tensorflow/python/ops/batch_ops_test.py
python3 tensorflow/tensorflow/python/ops/bincount_ops_test.py
python3 tensorflow/tensorflow/python/ops/bitwise_ops_test.py
python3 tensorflow/tensorflow/python/ops/clip_ops_test.py
python3 tensorflow/tensorflow/python/ops/clustering_ops_test.py
python3 tensorflow/tensorflow/python/ops/collective_ops_gpu_test.py
python3 tensorflow/tensorflow/python/ops/collective_ops_test.py
python3 tensorflow/tensorflow/python/ops/collective_ops_xla_test.py
python3 tensorflow/tensorflow/python/ops/control_flow_ops_test.py
python3 tensorflow/tensorflow/python/ops/control_flow_v2_disable_test.py
python3 tensorflow/tensorflow/python/ops/control_flow_v2_enable_test.py
python3 tensorflow/tensorflow/python/ops/control_flow_v2_toggles_test.py
python3 tensorflow/tensorflow/python/ops/dequantize_op_test.py
python3 tensorflow/tensorflow/python/ops/functional_ops_test.py
python3 tensorflow/tensorflow/python/ops/gradients_test.py
python3 tensorflow/tensorflow/python/ops/gradient_checker_v2_test.py
python3 tensorflow/tensorflow/python/ops/histogram_ops_test.py
python3 tensorflow/tensorflow/python/ops/image_grad_deterministic_test.py
python3 tensorflow/tensorflow/python/ops/image_grad_test.py
python3 tensorflow/tensorflow/python/ops/image_ops_test.py
python3 tensorflow/tensorflow/python/ops/losses/util_test.py
python3 tensorflow/tensorflow/python/ops/numpy_ops/integration_test/public_symbol_test.py
python3 tensorflow/tensorflow/python/ops/numpy_ops/np_arrays_test.py
python3 tensorflow/tensorflow/python/ops/numpy_ops/np_array_ops_test.py
python3 tensorflow/tensorflow/python/ops/numpy_ops/np_interop_test.py
python3 tensorflow/tensorflow/python/ops/numpy_ops/np_logic_test.py
python3 tensorflow/tensorflow/python/ops/numpy_ops/np_math_ops_test.py
python3 tensorflow/tensorflow/python/ops/numpy_ops/np_random_test.py
python3 tensorflow/tensorflow/python/ops/numpy_ops/np_utils_test.py
python3 tensorflow/tensorflow/python/ops/ragged/convert_to_tensor_or_ragged_tensor_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_batch_gather_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_boolean_mask_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_concat_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_constant_value_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_cross_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_dispatch_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_dynamic_partition_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_eager_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_expand_dims_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_from_sparse_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_from_tensor_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_gather_nd_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_gather_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_map_flat_values_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_map_fn_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_merge_dims_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_one_hot_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_operators_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_placeholder_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_print_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_range_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_rank_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_reduce_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_row_lengths_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_row_splits_to_segment_ids_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_segment_ids_to_row_splits_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_segment_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_size_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_squeeze_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_stack_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_tensor_bounding_shape_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_tensor_shape_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_tensor_supported_values_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_tensor_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_tile_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_to_sparse_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_to_tensor_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_util_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_where_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/row_partition_test.py
python3 tensorflow/tensorflow/python/ops/ragged/strings_reduce_join_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_const_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_getitem_test.py
python3 tensorflow/tensorflow/python/ops/ragged/ragged_reverse_op_test.py
python3 tensorflow/tensorflow/python/ops/ragged/string_ngrams_op_test.py
python3 tensorflow/tensorflow/python/ops/init_ops_test.py
python3 tensorflow/tensorflow/python/ops/init_ops_v2_test.py
python3 tensorflow/tensorflow/python/ops/math_grad_test.py
python3 tensorflow/tensorflow/python/ops/math_ops_linspace_test.py
python3 tensorflow/tensorflow/python/ops/math_ops_test.py
python3 tensorflow/tensorflow/python/ops/nccl_ops_test.py
python3 tensorflow/tensorflow/python/ops/nn_batchnorm_test.py
python3 tensorflow/tensorflow/python/ops/nn_fused_batchnorm_test.py
python3 tensorflow/tensorflow/python/ops/nn_grad_test.py
python3 tensorflow/tensorflow/python/ops/nn_loss_scaling_utilities_test.py
python3 tensorflow/tensorflow/python/ops/nn_test.py
python3 tensorflow/tensorflow/python/ops/nn_xent_test.py
python3 tensorflow/tensorflow/python/ops/op_selector_test.py
python3 tensorflow/tensorflow/python/ops/parallel_for/array_test.py
python3 tensorflow/tensorflow/python/ops/parallel_for/control_flow_ops_test.py
python3 tensorflow/tensorflow/python/ops/parallel_for/gradients_test.py
python3 tensorflow/tensorflow/python/ops/parallel_for/math_test.py
python3 tensorflow/tensorflow/python/ops/parallel_for/xla_control_flow_ops_test.py
python3 tensorflow/tensorflow/python/ops/quantized_conv_ops_test.py
python3 tensorflow/tensorflow/python/ops/quantized_ops_test.py
python3 tensorflow/tensorflow/python/ops/raw_ops_test.py
python3 tensorflow/tensorflow/python/ops/rnn_grad_test.py
python3 tensorflow/tensorflow/python/ops/script_ops_test.py
python3 tensorflow/tensorflow/python/ops/sobol_ops_test.py
python3 tensorflow/tensorflow/python/ops/sort_ops_test.py
python3 tensorflow/tensorflow/python/ops/sparse_ops_test.py
python3 tensorflow/tensorflow/python/ops/special_math_ops_test.py
python3 tensorflow/tensorflow/python/ops/stateful_random_ops_test.py
python3 tensorflow/tensorflow/python/ops/structured/structured_tensor_slice_test.py
python3 tensorflow/tensorflow/python/ops/structured/structured_tensor_spec_test.py
python3 tensorflow/tensorflow/python/ops/structured/structured_tensor_test.py
python3 tensorflow/tensorflow/python/ops/tensor_array_ops_test.py
python3 tensorflow/tensorflow/python/ops/v1_compat_tests/gradient_checker_test.py
python3 tensorflow/tensorflow/python/ops/variable_spec_test.py
python3 tensorflow/tensorflow/python/platform/app_test.py
python3 tensorflow/tensorflow/python/platform/benchmark_test.py
python3 tensorflow/tensorflow/python/platform/build_info_test.py
python3 tensorflow/tensorflow/python/platform/flags_test.py
python3 tensorflow/tensorflow/python/platform/logging_test.py
python3 tensorflow/tensorflow/python/platform/resource_loader_test.py
python3 tensorflow/tensorflow/python/platform/stacktrace_handler_test.py
python3 tensorflow/tensorflow/python/platform/sysconfig_test.py
python3 tensorflow/tensorflow/python/profiler/integration_test/profiler_api_test.py
python3 tensorflow/tensorflow/python/profiler/internal/print_model_analysis_test.py
python3 tensorflow/tensorflow/python/profiler/internal/run_metadata_test.py
python3 tensorflow/tensorflow/python/profiler/model_analyzer_test.py
python3 tensorflow/tensorflow/python/profiler/pprof_profiler_test.py
python3 tensorflow/tensorflow/python/profiler/profiler_client_test.py
python3 tensorflow/tensorflow/python/profiler/profiler_test.py
python3 tensorflow/tensorflow/python/profiler/profiler_v2_test.py
python3 tensorflow/tensorflow/python/profiler/profile_context_test.py
python3 tensorflow/tensorflow/python/profiler/tfprof_logger_test.py
python3 tensorflow/tensorflow/python/saved_model/model_utils/export_output_test.py
python3 tensorflow/tensorflow/python/saved_model/model_utils/export_test.py
python3 tensorflow/tensorflow/python/saved_model/model_utils/mode_keys_test.py
python3 tensorflow/tensorflow/python/saved_model/loader_test.py
python3 tensorflow/tensorflow/python/saved_model/load_test.py
python3 tensorflow/tensorflow/python/saved_model/load_v1_in_v2_test.py
python3 tensorflow/tensorflow/python/saved_model/method_name_updater_test.py
python3 tensorflow/tensorflow/python/saved_model/nested_structure_coder_test.py
python3 tensorflow/tensorflow/python/saved_model/revived_types_test.py
python3 tensorflow/tensorflow/python/saved_model/saved_model_test.py
python3 tensorflow/tensorflow/python/saved_model/save_context_test.py
python3 tensorflow/tensorflow/python/saved_model/save_test.py
python3 tensorflow/tensorflow/python/saved_model/signature_def_utils_test.py
python3 tensorflow/tensorflow/python/saved_model/simple_save_test.py
python3 tensorflow/tensorflow/python/saved_model/utils_test.py
python3 tensorflow/tensorflow/python/summary/plugin_asset_test.py
python3 tensorflow/tensorflow/python/summary/summary_iterator_test.py
python3 tensorflow/tensorflow/python/summary/summary_test.py
python3 tensorflow/tensorflow/python/summary/writer/writer_test.py
python3 tensorflow/tensorflow/python/tf_program/tests/mlir_gen_test.py
python3 tensorflow/tensorflow/python/tools/api/generator/create_python_api_test.py
python3 tensorflow/tensorflow/python/tools/api/generator/doc_srcs_test.py
python3 tensorflow/tensorflow/python/tools/api/generator/output_init_files_test.py
python3 tensorflow/tensorflow/python/tools/freeze_graph_test.py
python3 tensorflow/tensorflow/python/tools/optimize_for_inference_test.py
python3 tensorflow/tensorflow/python/tools/print_selective_registration_header_test.py
python3 tensorflow/tensorflow/python/tools/saved_model_cli_test.py
python3 tensorflow/tensorflow/python/tools/saved_model_utils_test.py
python3 tensorflow/tensorflow/python/tools/strip_unused_test.py
python3 tensorflow/tensorflow/python/tpu/async_checkpoint_test.py
python3 tensorflow/tensorflow/python/tpu/bfloat16_test.py
python3 tensorflow/tensorflow/python/tpu/client/client_test.py
python3 tensorflow/tensorflow/python/tpu/datasets_test.py
python3 tensorflow/tensorflow/python/tpu/feature_column_test.py
python3 tensorflow/tensorflow/python/tpu/feature_column_v2_test.py
python3 tensorflow/tensorflow/python/tpu/topology_test.py
python3 tensorflow/tensorflow/python/tpu/tpu_embedding_v2_correctness_test.py
python3 tensorflow/tensorflow/python/tpu/tpu_embedding_v2_cpu_test.py
python3 tensorflow/tensorflow/python/tpu/tpu_embedding_v2_test.py
python3 tensorflow/tensorflow/python/tpu/tpu_embedding_v2_utils_test.py
python3 tensorflow/tensorflow/python/tpu/tpu_infeed_test.py
python3 tensorflow/tensorflow/python/tpu/tpu_outside_compilation_test.py
python3 tensorflow/tensorflow/python/tpu/tpu_sharding_test.py
python3 tensorflow/tensorflow/python/tpu/tpu_test.py
python3 tensorflow/tensorflow/python/tpu/tpu_test_wrapper_test.py
python3 tensorflow/tensorflow/python/training/adadelta_test.py
python3 tensorflow/tensorflow/python/training/adagrad_da_test.py
python3 tensorflow/tensorflow/python/training/adagrad_test.py
python3 tensorflow/tensorflow/python/training/adam_test.py
python3 tensorflow/tensorflow/python/training/basic_loops_test.py
python3 tensorflow/tensorflow/python/training/basic_session_run_hooks_test.py
python3 tensorflow/tensorflow/python/training/checkpoint_management_test.py
python3 tensorflow/tensorflow/python/training/checkpoint_ops_test.py
python3 tensorflow/tensorflow/python/training/checkpoint_utils_test.py
python3 tensorflow/tensorflow/python/training/coordinator_test.py
python3 tensorflow/tensorflow/python/training/device_setter_test.py
python3 tensorflow/tensorflow/python/training/evaluation_test.py
python3 tensorflow/tensorflow/python/training/experimental/loss_scale_optimizer_test.py
python3 tensorflow/tensorflow/python/training/experimental/loss_scale_test.py
python3 tensorflow/tensorflow/python/training/experimental/loss_scaling_gradient_tape_test.py
python3 tensorflow/tensorflow/python/training/experimental/mixed_precision_test.py
python3 tensorflow/tensorflow/python/training/ftrl_test.py
python3 tensorflow/tensorflow/python/training/gradient_descent_test.py
python3 tensorflow/tensorflow/python/training/input_test.py
python3 tensorflow/tensorflow/python/training/localhost_cluster_performance_test.py
python3 tensorflow/tensorflow/python/training/momentum_test.py
python3 tensorflow/tensorflow/python/training/monitored_session_test.py
python3 tensorflow/tensorflow/python/training/moving_averages_test.py
python3 tensorflow/tensorflow/python/training/optimizer_test.py
python3 tensorflow/tensorflow/python/training/proximal_adagrad_test.py
python3 tensorflow/tensorflow/python/training/proximal_gradient_descent_test.py
python3 tensorflow/tensorflow/python/training/quantize_training_test.py
python3 tensorflow/tensorflow/python/training/queue_runner_test.py
python3 tensorflow/tensorflow/python/training/rmsprop_test.py
python3 tensorflow/tensorflow/python/training/saver_large_partitioned_variable_test.py
python3 tensorflow/tensorflow/python/training/saver_large_variable_test.py
python3 tensorflow/tensorflow/python/training/saver_test.py
python3 tensorflow/tensorflow/python/training/saving/functional_saver_test.py
python3 tensorflow/tensorflow/python/training/server_lib_multiple_containers_test.py
python3 tensorflow/tensorflow/python/training/server_lib_same_variables_clear_container_test.py
python3 tensorflow/tensorflow/python/training/server_lib_same_variables_clear_test.py
python3 tensorflow/tensorflow/python/training/server_lib_same_variables_no_clear_test.py
python3 tensorflow/tensorflow/python/training/server_lib_sparse_job_test.py
python3 tensorflow/tensorflow/python/training/server_lib_test.py
python3 tensorflow/tensorflow/python/training/session_manager_test.py
python3 tensorflow/tensorflow/python/training/slot_creator_test.py
python3 tensorflow/tensorflow/python/training/supervisor_test.py
python3 tensorflow/tensorflow/python/training/sync_replicas_optimizer_test.py
python3 tensorflow/tensorflow/python/training/tensorboard_logging_test.py
python3 tensorflow/tensorflow/python/training/tracking/base_test.py
python3 tensorflow/tensorflow/python/training/tracking/benchmarks_test.py
python3 tensorflow/tensorflow/python/training/tracking/data_structures_test.py
python3 tensorflow/tensorflow/python/training/tracking/python_state_test.py
python3 tensorflow/tensorflow/python/training/tracking/tracking_test.py
python3 tensorflow/tensorflow/python/training/tracking/util_test.py
python3 tensorflow/tensorflow/python/training/tracking/util_with_v1_optimizers_test.py
python3 tensorflow/tensorflow/python/training/training_ops_test.py
python3 tensorflow/tensorflow/python/training/training_util_test.py
python3 tensorflow/tensorflow/python/training/warm_starting_util_test.py
python3 tensorflow/tensorflow/python/util/decorator_utils_test.py
python3 tensorflow/tensorflow/python/util/deprecation_test.py
python3 tensorflow/tensorflow/python/util/dispatch_test.py
python3 tensorflow/tensorflow/python/util/example_parser_configuration_test.py
python3 tensorflow/tensorflow/python/util/function_parameter_canonicalizer_test.py
python3 tensorflow/tensorflow/python/util/function_utils_test.py
python3 tensorflow/tensorflow/python/util/keyword_args_test.py
python3 tensorflow/tensorflow/python/util/lock_util_test.py
python3 tensorflow/tensorflow/python/util/module_wrapper_test.py
python3 tensorflow/tensorflow/python/util/nest_test.py
python3 tensorflow/tensorflow/python/util/object_identity_test.py
python3 tensorflow/tensorflow/python/util/protobuf/compare_test.py
python3 tensorflow/tensorflow/python/util/serialization_test.py
python3 tensorflow/tensorflow/python/util/tf_contextlib_test.py
python3 tensorflow/tensorflow/python/util/tf_decorator_test.py
python3 tensorflow/tensorflow/python/util/tf_export_test.py
python3 tensorflow/tensorflow/python/util/tf_inspect_test.py
python3 tensorflow/tensorflow/python/util/tf_should_use_test.py
python3 tensorflow/tensorflow/python/util/tf_stack_test.py
